### ISSUE TITLE
Enhance iocontrol_v2 for ATC

### ISSUE THREAD

**Issue by alkabal** [machinekit/machinekit-hal#172]
Hi

I'm not sur if this is good place for this discution.

I like to ask if this is possible to add some control to iocontrol_v2.cc

If possible i like to have a value that return the last existing tool in table and  synch when the table is parsed.

something like this
iocontrol_data->tool_table_last_one

At same time if possible to add a signal that can be ask tool change from external component like this
 iocontrol_data->tool_change_ask_by_pdnt

doing something like

```
if  iocontrol_data.tool_change_ask_by_pdnt = 1
then  
iocontrol_data.prep_number =  iocontrol_data.tool_number + 1 
        if  iocontrol_data.prep_number > iocontrol_data.tool_table_last_one 
        then
           iocontrol_data.prep_number = 1
        endif
 iocontrol_data.tool_prepare = 1
 iocontrol_data.tool_change = 1
endif

```
I'm not sure i can do this myself but in any case i ask beforre start to code something unwanted

Br

**Comment by alkabal** [comment]
Or possible to do a iov3 ?

**Comment by ArcEye** [comment]
There is nothing to stop you adapting iocontrol.cc any way you wish and using your copy.

The problem with changing an existing component within Machinekit the way you want, is that it just provides you with a workaround you could do for yourself if you approached things another way.
It would not be of any general usefulness to others.

Don't know why you ask about iocontrol_v2.cc, that originated in linuxcnc for better error reporting and probably for use with remapping, but no one uses it.
It will not help you with errors in your current method, you need to change your method so that it fits with the way that iocontrol works.

There is a lot of confused thinking going on and I have tried to tell you before that the pendant is an irrelevance.

You need to get the tool changer to change to the requested tool using TxM6 and then have your pendant issue the same commands.
The tool changer component does not need to know what the last tool in the tool table is, it has a fixed number of tools and once homed or otherwise initialised, it always knows where it is.

The big problem seems to be, that you are using a very limited pendant as a substitute for a proper GUI with keyboard and mouse.
I can only imagine that it is not capable of issuing the right commands, through limited capacity in buttons or macro's and everything that follows is attempting to mitigate this.

The rack tooling issue is pretty much separate and might be better dealt with by a second component which just deals with tool change requests above 6.
The ATC component could determine the tool number requested and if a rack tool, pass the request on.

Until you do this, you are always going to have an error requesting a tool above No 6, or any tool number that is not in the tool table.

**Comment by alkabal** [comment]
Finally I have think about trigger a Hal to mdi with TC make possible to send M6T0 so I can now reset GUI by this way without changing iocontrol source code 

First test seem to be good

Can you help if you are ok For odd even implementing ?

**Comment by ArcEye** [comment]
> Can you help if you are ok For odd even implementing ?

The reason I had different size moves between tools, was that my ATC turret had 4 cutting tools at 90deg to the workpiece and 4 VDI 20 slots to take drills or VDI tool holders.
The tools were alternate with the slots and the slots were arranged with centre at workpiece centre height but the tools were arranged so that tool tip was at centre height.

If all your tools are cutting tools and all the same size, you may indeed have equal spacing between tool numbers so not need different distances.

It looks like a huge amount of your problems are to do with the step calculation leading to division errors.
If your tools are indeed exactly 60 deg apart, have you tried making the axis angular and commanding incremental moves of 60 degrees?
(ie. don't tell it to go to 120 degrees, because it could decide to go backwards via the shortest route, just tell it to advance by 60 degrees x number of tool positions to advance.)

**Comment by alkabal** [comment]
Ok i understand now for your tc type even odd 

Cortini ATC is equal distance

I have 0 problem with move and calc I have add error detection for external problem like crash from tool and pieces, sensor defect or inconsistencies state from GUI 

I have take many many attention for homing from any starting position else if not on the bracket 

Homing to any asked valid M6Tx fond home and set this tool automatically 

Homing can be asked automatically immediately after machine homed 

Homing can finish correctly if sensor fail but come back later

Next I have done and stress a lot the tool change move system and make possible again to resolve automatically if something append with sensor home again automatically (if sensor comme back) and set the correct tool (now this feature is wanted locked by the error system after 2 full rev)

After this I have added error detection so now if something is not in a normal range, as soon as possible stop gcode program and or TC movement and alert user

Finished by try to restart correctly after all possible errors Without restarting machinekit.

All of this use only program_stop and some homing flags for keep GUI without freeze

The next is implementing now a reset tool number for emc/gui, with my actual system this is not really needed because I have constructed all without this feature and make possible to manage like it is.

This function is planned to implement without remove other condition check and make this a secondary security.



My attempt is to Create a flexible and secured component for “ATC past to pawl with one sensor for tool 1” Compatible with axis Cetus xmotion and pendant xhc-whb04-6 

In this way I think add even move can be interesting for other one and I really like if you can test on your ATC


From MK component exemple I have encountered many issue with wrong movement (I think badly constructed waiting delay for my first attemp) 

Rtapi_print_msg does not work at all with stretch

GUI and EMC freezing easily with some estop condition or problem from atc 

Gcode Program execution badly locked if something is wrong

For some reason if you have too much tool in your table and ask one one this the original tc says ok and gcode program can continu

For sure some of this are because I have applied many many stress to the system but in this way I have try to check all possible error and found a safe solution 







One problem stay in place If something append for exemple 
current tool 1 (is on the sensor)
Ask tool 2 
lock the movement manually 
Ask tool 3
No error occurs because we need to view sensor again at tool 1 after one full rev before applying calc and detect the error 

For This i think about finally move always to tool 1 before  going to Other tool for check sensor and position accuracy for all change (maybe later)



Only one calc make some problem in particular state, but this append only with many many stress applied to TC sw/hw and GUI at same time 

My fabs Float compares is wrong If result are -0.35 for exemple

And another one problem exists without the use of reset tool number for emc/gui I have some trouble to keep locked program execution If try to restart gcode program many time and at same time I have the need to alert user and wait M6Tx from GUI before Gcode can restart again. 
I’m sure is possible but I can’t found the good condition without having other issue
The tool number reset I think can bypass this problem but I like to found a solution without this lol


Sorry for very very bad English and very long message. It’s really difficult for me to explain correctly I hope this is understandable 

Many many thanks for your time, Br


Ps: I send you later my improved code

**Comment by alkabal** [comment]
With M6T0 and use internal loopback for prepare/prepared now all is perfect no more strange issue !!

thanks a lot you help me to understand many things

**Comment by alkabal** [comment]
My ATC work like this.

```
move =
     position_req += (tool_angle * moves) + additional_factor; 
return for lock
     position_req -= fudge_factor; 


1 move 60° +4° wait delay retract -14°
2 moves (60°*2) +4° wait delay retract -14°
2 moves (60°*3) +4° wait delay retract -14°
```

so at the end all work very fine.

I have some trouble to understand how work yours calc with this value

param rw float odd_move = 22.2 
param rw float even_move = 24

**Comment by ArcEye** [comment]
If you have a linear axis, its units are mm, not degrees.

Those figures are commanded moves in axis units (mm) between stations.
I also have an 8 station ATC, so the move is shorter.
The rest is down to the gearing etc.

If you have a linear axis and try to calculate moves in degrees, only madness can follow :stuck_out_tongue_closed_eyes:

**Comment by alkabal** [comment]
Yes I have set linear axis in mm

But I have take attention for stepper setting 360mm = 1 exact full revolution 

All work 100% fine I’m sure as possible 

You real tool angle are ?

Even 48
Odd 44.4

The result is 369,6 ???

**Comment by ArcEye** [comment]
There are no angles, it is a linear axis.

I measured the distance necessary to be moved between each tool and use that.
There is a locking pawl, you only need to be beyond that and move back to lock in position.
You don't need to have precise movements, it can only lock in one place

Again
If you have a linear axis and try to calculate moves in degrees, only madness can follow :stuck_out_tongue_closed_eyes:

**Comment by alkabal** [comment]
I really suggest you can try to use my code that can work in your situation with tuning fudge_factor and additional_factor

Put 45 for tool_angle
Do not touch the other for now

Keep In mind with good stepper config and linear axis you can 

ask position_req = 360 and tune stepper for having a full revolution and you are now ok for use some more real value

After ask 2x 3x etc position_req = 360 and see if you are ok or not


Now I’m sure your setting are not enough precise and this make many trouble for understand how component work

I send you soon my all in one tc.comp with all settings needed at the top of the file

Br



> If you have a linear axis and try to calculate moves in degrees, only madness can follow
>

**Comment by alkabal** [comment]
Off course I understand your code work correctly ! 

But as my “now understanding” 
your tc is not really compliant with iocontrol 
you use some approximative value for move and use some divisor
Stepper settings approximative
Bad waiting delay method


Sorry lol I hope I’m right and especially I hope not angry you

**Comment by ArcEye** [comment]
> you use some approximative value for move and use some divisor Stepper settings approximative

In what way is `22.2` an approximate value? It is the value required for **my** ATC.

> your tc is not really compliant with iocontrol

From someone who thought writing to an iocontrol OUT pin would change the value in iocontrol !!

> Bad waiting delay method 

From someone who calls `sleep()` in the middle of a real time component !!

I don't have time for this, if you want to change iocontrol to get around deficiencies in your bastardisation of my toolchange component and cater for your obsession with using a dumb pendant to do everything, go ahead.
Just don't expect it to be adopted.

**Comment by alkabal** [comment]
Hi sorry i see you not like my message

Please forgot the first ask for change iocontrol and pendant issue, with this discution i have understand many things and found good way for manage what i wan't and wha't i think needed without change anithing in MK source code, really you have all my gratitude !! (i'm sleepless from few days and my brain is not allways accurate i know)

only last question have you try to ask 8 move from your code ? (start from tool 1 and ask 8 move for return to tool 1)

Have a nice day and really sorry for time loosing.

**Comment by alkabal** [comment]
Finally I have understand how your calc and move are done so ok if you ask 8 move all is ok because you move 1 tool wait lock before go to 2 lock  etc for each tool

My system ask the full move before go to locked position

**Comment by alkabal** [comment]
https://youtu.be/TAqe_k-iC7Y

**Comment by alkabal** [comment]
I have try juste now to set axis as ANGULAR and all for fine 100%

**Comment by alkabal** [comment]
Now implemented mode one tool by one tool with odd even

**Comment by alkabal** [comment]
With some help I can tu to do other working mode 
I think about an all in one solution
